### ISSUE TITLE
JSON API doesn't reference multiple images in a post

### ISSUE THREAD

**Issue by hounsell** [ctrlcctrlv/infinity#113]
For example, in a thread where a post may contain multiple attached images (such as this one currently in /meta/ - https://8chan.co/meta/res/1874.html) the JSON (ie https://8chan.co/meta/res/1874.json) only references the first image.

I understand that this is probably to keep a reasonable level of compatibility with the halfchan API, and that you can still assume there's more images on a post thanks to the -0 in the filename, but maybe we could introduce some extra fields for multi-image posts? Maybe a comma-separated collection of fields (ie, filename, size, etc) for each extra image?

**Comment by ctrlcctrlv** [comment]
i fixed this a long time ago
