### ISSUE TITLE
A new postbox

### ISSUE THREAD

**Issue by czaks** [ctrlcctrlv/infinity#185]
the current postbox is kinda old-fashioned and there are a few bugs. it's also not too good with regard to multiple image support.

a new postbox project would replace quick reply, unifying two different applets into one. quick reply would have two flavours: on desktops it would be a movable field, or a topbox, on mobiles it would be both (?) topbox and a bottombox.

http://int.vichan.net/devel/src/1sttsqob.vichan.png <- this is my early project

the new postbox may be disableable if a person feels old-fashioned actually :)

i'm still looking for good inspirations

**Comment by ctrlcctrlv** [comment]
done (but not how @czaks intended, lel)
