### ISSUE TITLE
Feature Request: Faq/Wiki for board owners/mods/volunteers to edit.

### ISSUE THREAD

**Issue by finbe** [ctrlcctrlv/infinity#335]
Something for the board moderators/volunteers/whatever to edit that would show up under /boardname/faq or /boardname/wiki . I see this as a much more permanent solution to the stickies currently in use on most boards on 8chan for scheduling events, posting rules, and answering questions.

**Comment by bui** [comment]
is the rules page not sufficient?

**Comment by finbe** [comment]
Huh, never noticed that in use. Should probably mark this as closed then.
