### ISSUE TITLE
Attention bar

### ISSUE THREAD

**Issue by czwarty** [ctrlcctrlv/infinity#341]
How to add attention bar to 8chan board? I paste it to stylesheet but it doesn't work.

**Comment by AnonTheCuck** [comment]
Do php rebuild.php from inside the tools folder. It's because main.js is missing.

**Comment by AnonTheCuck** [comment]
Close your issue and for future reference, ask questions in http://8chan.co/8code

**Comment by czwarty** [comment]
Sorry, I've been away for long time due to personal issues. How to exactly do this, step by step? I'm totally ignorant in this matter.

**Comment by AnonTheCuck** [comment]
What are you talking about?

**Comment by czaks** [comment]
attention bar has been removed from vichan upstream as of 5.0 branching. infinity merged 5.0 fully.
thus, there is no easy way to enable attention bar, i'd even say, it's impossible, unless 8chan backports it from 4.5 branch and enables it in config.
i don't really think we should do this. attention bar is specific only to polish and slovak chans.

**Comment by czwarty** [comment]
okay well, thanks
