### ISSUE TITLE
favorites.js issue

### ISSUE THREAD

**Issue by yrrah2** [ctrlcctrlv/infinity#346]
When the function add_favorites() runs the favorite-boards span is appended onto the end of the boardlist which is not where it is when the page loads originally. 

This means 
span.favorite-boards:nth-child(6) 
becomes 
span.favorite-boards:nth-child(7) 
after favoriting a board.

It also means 
div.boardlist:nth-child(1) > span:nth-child(7) 
becomes
div.boardlist:nth-child(1) > span:nth-child(6)
after favoriting a board.

This in turn means that the css that relies on these rules will break each time a board is favorited.

**Comment by AlicesWrath** [comment]
Not sure if related, but my favourite boards list keeps deleting itself. :(

**Comment by bbielsa** [comment]
@yrrah2 I have fixed the problem and I will be creating a pull request for the update. The guy who wrote favorites.js was not paying attention.

@AlicesWrath The boards are saved in localstorage. Make sure that you are not browsing in Private Mode or Incognito. As I understand it most browsers will delete the localstorage when in these modes. If you are still seeing this issue there may be something else wrong, but I don't have much information to go off of.

**Comment by bbielsa** [comment]
Simple fix. Sorry it took so long, I was busy with uni stuff.
