### ISSUE TITLE
Stronger ban tracking

### ISSUE THREAD

**Issue by Imagebard** [ctrlcctrlv/infinity#366]
An epidemic problem with imageboards(and indeed, 8chan) was easy ban evading.
Something must be done, but people here are very tech savvy

I don't have much good ideas, mostly extreme solutions that should only be avaliable to Global Volunteers. Storing https://en.wikipedia.org/wiki/Device_fingerprint or use of https://en.wikipedia.org/wiki/Evercookie for people posting illegal content might be reasonable.

**Comment by bui** [comment]
can we close this issue

**Comment by Imagebard** [comment]
Ban evader detected

**Comment by bui** [comment]
US government agent detected

but really, what makes you think implementing something like this will be accepted by even the non-autists on 8chan?

**Comment by Imagebard** [comment]
@bui:Because maybe i want to browse 8chan without CP, or maybe without a domain registrar taking our website, or maybe i just want to actually enforce rules on my board instead of just encouraging shitposting.

Good thing that ctrlcctrlv added the wontfix label without any comment on it.
