### ISSUE TITLE
8ch.net provides unpredictable thumbnail extension 

### ISSUE THREAD

**Issue by peryton** [ctrlcctrlv/infinity#387]
I'm having trouble parsing the 8ch.net JSON API output in particular, so I'm not sure if this is an infinity bug or an 8ch deployment issue. This might not reproduce on another server.

### Thumbnails are not available with a consistent extension scheme

**Severity/Impact**: 
*Moderate*.  Consumers of the 8ch.net JSON API such as applications cannot display thumbnails reliably.  

**Desired behavior:**
Extension for thumbnail files should be defined in `$config['thumb_ext']`, or inherited from uploaded image. This behavior is defined in `inc/config.php` and implemented in `post.php`.

**Actual behavior:**
Inconsistent with the scheme defined in `inc/config.php`.  From my experiments, most thumbnail images seem to be available with a JPG extension, including PNGs (with transparency!).  However, sometimes thumbnail GIFs are converted to still JPGs (and available with a .JPG extension), sometimes they stay as a .GIF extension and are animated.

**Comment by ctrlcctrlv** [comment]
It's because the format changed. The thumbnail used to be based on the type of original image, then was changed to JPG for all images. That's why the different behavior.

**Comment by peryton** [comment]
Seems to be fixed for all but very old posts.
