### ISSUE TITLE
[Suggestion] Edit favorites order

### ISSUE THREAD

**Issue by yrrah2** [ctrlcctrlv/infinity#389]
If it is at all possible to view your favorites in the options menu and change their order I am sure it would make many users as well as mine much simpler.

**Comment by Kyokou** [comment]
+1 

Having recently beginning to use the favorites feature (slightly more convenient than using a keyword for "8 %s") this would be nice to have.

**Comment by yrrah2** [comment]
I am working on a script right now at https://github.com/yrrah2/change-favorites-test
I don't if the merge will be made when I am done but you can use the script there.
