### ISSUE TITLE
Possible to disable a moderator account by creating a board with same username

### ISSUE THREAD

**Issue by bugzeeolboy** [ctrlcctrlv/infinity#398]
Discovered this when I was a mod on some other board and I created a board with the same username as my volunteer on the other board.

**Comment by ctrlcctrlv** [comment]
How long ago? This was supposed to have been patched in https://github.com/ctrlcctrlv/infinity/commit/6ed13f3fb0cc8921bb8dcbf87626cb734e90ef8f

Please give exact steps to reproduction.

**Comment by bugzeeolboy** [comment]
1. someone just volunteered me on their board, gave me the password, I changed it to one I wanted
2. I created a board with the same username and random password as the volunteer
3. tried logging into my account with old password, didn't work
4. logged into my account with new password
5. I only see the board I created, not the one I am a volunteer in

**Comment by ctrlcctrlv** [comment]
Can you please tell me the account name that is affected?

This is a serious bug if it's really happening, you could easily shadow global volunteer/admin accounts

**Comment by bugzeeolboy** [comment]
username is 'donkus'

**Comment by ctrlcctrlv** [comment]
The DB only has one row for donkus, owner of /calc/

Are you SURE that the volunteer account and owner account are exactly the same? Because if so it deleted your previous account which should be impossible

**Comment by bugzeeolboy** [comment]
I'm sure, firefox remembered my password for donkus, which was the old password that doesn't work anymore (volunteer of another board).

**Comment by ctrlcctrlv** [comment]
Is it possible that the other board owner just deleted your account? Please try asking him because I can't get this to happen here

(you can try it yourself: my username on 8chan is copypaste, try creating a board with that username or a volunteer, it rejects both)

**Comment by bugzeeolboy** [comment]
It is possible that he deleted my account. Still waiting for a reply from him.

**Comment by bugzeeolboy** [comment]
Yes, he deleted the account. What a bad coincidence. Sorry about that

**Comment by ctrlcctrlv** [comment]
No problem :3
