### ISSUE TITLE
immediately after informing TOR users that they cannot upload, the image selected should be purged...

### ISSUE THREAD

**Issue by infoburp** [ctrlcctrlv/infinity#402]
..to allow them to just hit post again..

**Comment by infoburp** [comment]
or at least there should be a simpler way to clear the attachment pickers, it's not entirely clear how to do this right now, could be a bit of an F5 moment...

**Comment by bui** [comment]
open file picker + press esc

but if you're using tor you should already know you can't upload images...

**Comment by infoburp** [comment]
That's a perfectly valid point,  but is that any reason to penalise the user who didn't know? It's not a long, drawn out fix I'm suggesting......

**Comment by 8n-tech** [comment]
Why are TOR users ever given the option to upload to begin with? It's a 
flawed user interface. It'd be like if Google AdSense had a button to 
"withdraw $1000" and then when you click it it tells you "you need $1000 
in your account to do that". It's stupid. Surely the system can know 
you're using TOR before you click submit.

**Comment by infoburp** [comment]
My point exactly, it is flawed, but it's also a new feature that's not fully fleshed out yet, one to work on though..

**Comment by infoburp** [comment]
wheels is clearly a supporter of tor so let's make it so.

**Comment by AnonTheCuck** [comment]
Every page you look at with the exception of the mod pages are static. The
only way to have the file picker omitted would be to implement it in
javascript, which must people who use tor have disabled.

**Comment by bui** [comment]
non-tor users might also have js disabled though
there doesn't appear to be any reasonable way to "solve" this

**Comment by infoburp** [comment]
good points being raised here. is a server-side setting for noscript not possible? if not why not? it could be a checkbox in the options bit..

**Comment by infoburp** [comment]
also handy for non-tor, as you say @bui

**Comment by AnonTheCuck** [comment]
What would be a solution would be PHP wise, instead of throwing an error,
omit the image and post the text anyways and display a message along the
lines of: "Uploading flies over Tor has been disabled. We have
automatically removed your file for you."

**Comment by bui** [comment]
@AnonTheCuck I don't think that's good, it could lead to confusion for others, especially if the image is related to the text

**Comment by AnonTheCuck** [comment]
My only other idea would be to revamp the error page to warn them that
files are disabled, show the post, and ask if they still want to post it.
(Again, this only happens if they try to upload a file over Tor, which
should only happen once.)

**Comment by infoburp** [comment]
Sounds good to me, much better than how it is now..

**Comment by infoburp** [comment]
@bui could there not be a standard "oops, noob tor post!!" image or something?

**Comment by bui** [comment]
tbh this issue won't be valid any more once the ronin system (which allows tor users to upload) comes into place

**Comment by infoburp** [comment]
ah. explain more, please..

**Comment by bui** [comment]
https://8ch.net/ronin.html

**Comment by infoburp** [comment]
Cool beans... still this needs thought I think.. it's just not "slick"
right now..

On Sun, Feb 22, 2015 at 6:21 PM, Bui <notifications@github.com> wrote:

> https://8ch.net/ronin.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ctrlcctrlv/infinity/issues/402#issuecomment-75449259>.
>



-- 
Graeme Wolfendale
