### ISSUE TITLE
NSFW filters

### ISSUE THREAD

**Issue by anonfagola** [ctrlcctrlv/infinity#440]
I don't really know where to put this, but I'm programming an NSFW filter.
As in, in the General tab there will be checkbox for if you want NSFW boards or not.
If it's on, all of the top boards will only be boards that are SFW.
Also, when you visit a board that's NSFW, it will tell you a message similar to:
<b>This board has been labeled NSFW by its owner. Would you like to add it to your filter?</b>
Speaking of filter, if the NSFW option is checked, a textarea will appear where you can write your filters to all of the features above.
Of course, this option will be <b>turned off</b> by default, as boards are labeled NSFW by default (if I'm right), and most of the commonly used boards are labeled NSFW.
Currently, you can already find boards that are NSFW or not through the boards page.
Give me ideas for this feature in the comments. Thanks!

**Comment by ctrlcctrlv** [comment]
New boards page does this
