### ISSUE TITLE
All blank after instalation

### ISSUE THREAD

**Issue by pikkkkaaa** [ctrlcctrlv/infinity#442]
I've installed everything using the given instructions
But all pages are blank.
secrets.php is edited.

**Comment by anonfagola** [comment]
Do you have the DirectIO module?

**Comment by pikkkkaaa** [comment]
Actually, no.
I'm really noob, how do i install that?
http://php.net/manual/en/ref.dio.php says to download the "cvs repo" and then compile it, how?

**Comment by pikkkkaaa** [comment]
No, and i'm not able to install new PHP extensions on a shared hosting account (godaddy)
 Is there any way around this? I can change my php version.

**Comment by ctrlcctrlv** [comment]
You're completely insane if you think you can run infinity on godaddy hosting.
