### ISSUE TITLE
Links in favourites

### ISSUE THREAD

**Issue by yrrah2** [ctrlcctrlv/infinity#446]
Due to the favourites tab having custom input, you can now have links to things other than boards in your favourites.

![screenshot from 2015-03-26 16 48 19](https://cloud.githubusercontent.com/assets/9469469/6840158/41f84a02-d3d8-11e4-9d26-f99631bc99d7.png)

This is up to the user so it isn't really an issue but I would like to know everyone's thoughts whether they be that we should stylize non-board links, remove them or keep them the same.

Btw you can not go to links while clicking them in catalog mode.

**Comment by ctrlcctrlv** [comment]
this is cool, you would purposely have to enter the links so I do not think sanitation is necessary...
