### ISSUE TITLE
Big threads freeze the tab when inlining is enabled in options

### ISSUE THREAD

**Issue by sourcerect** [ctrlcctrlv/infinity#451]
Inlining is enabled. I'm hanging in the GG thread, which is rather large and active. As soon as a new post is added to the thread (via the [Update] button or by auto-update), the browser tab freezes and one of my CPU's cores maxes out. After about 3 seconds the post is displayed and it goes back to normal. The more posts that are being added, the longer it freezes. This also happens when the thread is first loaded. When inlining is disabled, no freezing occurs.

I ran a CPU profile and attempted to find the problem, given the minified JS. It seems as though [the jQuery call run by the assign_inline function](https://github.com/ctrlcctrlv/infinity/blob/5acafdf1b9ba4a564d814360d762625febece4f4/js/inline.js#L140-152) is taking too long. To test this, I copied [the query part](https://github.com/ctrlcctrlv/infinity/blob/5acafdf1b9ba4a564d814360d762625febece4f4/js/inline.js#L142) over to the chrome console and ran it, and sure enough, it freezes for a few seconds.

Chrome 41, Linux.

**Comment by ctrlcctrlv** [comment]
This is useful information. Several people have been reporting this, but now at least I know it's related to the inling feature because I oculdn't reproduce it earlier.
