### ISSUE TITLE
SVG Attachment - Feature Request

### ISSUE THREAD

**Issue by smalltock** [ctrlcctrlv/infinity#454]
I request that the ability to upload SVGs be implemented.
For vector images, SVG saves a lot of file space in comparison with high-resolution rasterizations.
It would allow other users better ability to make modifications of uploaded vector images.
I would prefer to upload SVGs rather than large PNGs in OC threads. That would save the hassle of rasterization and possibly linking the original SVG from an external server.

Most browsers, including Firefox and Chrom*, are able to render SVG images enclosed in \<img\> already, so there shouldn't need to be any trickery.

**Comment by czaks** [comment]
nice, how about XSS issues?

**Comment by bui** [comment]
@czaks [alnorris/SVG-Sanitizer](https://github.com/alnorris/SVG-Sanitizer)

**Comment by czaks** [comment]
@bui i like it

**Comment by majestrate** [comment]
I think it's a bad idea because of xml bombs

curl http://a.pomf.se/uxgywz.svg

**Comment by majestrate** [comment]
I hope that this motivates people to either fix xml parsers, the SVG format or just not use SVG ever again since it's a bad idea to have an XML based image format. https://gist.github.com/majestrate/84f8edf2a257c6fa5545

**Comment by czaks** [comment]
@majestrate and what if we strip ENTITY tags?

**Comment by majestrate** [comment]
@czaks That'd work for this case but with SVG it would probably be a never ending cat and mouse game of discovering ways to break SVG and then patching them.

**Comment by ctrlcctrlv** [comment]
Absolutely not.

**Comment by objarni** [comment]
How does launchpad manage svg issue attachments?
