### ISSUE TITLE
Max file size check incorrect

### ISSUE THREAD

**Issue by nyanpasu** [ctrlcctrlv/infinity#457]
Tried to post this file: http://a.pomf.se/wmhrux.webm

```
# du -b plastic_man.webm 
8820313	plastic_man.webm
```

Got this:

![pic](https://cloud.githubusercontent.com/assets/6234817/7075185/8716a4a2-df32-11e4-95ad-7f981f65c889.png)

Addtionally, it has failed a couple times like the way described in issue #223 first. I only got the error in pic related after a couple more attempts and a page refresh.

**Comment by bui** [comment]
uh, your webm is bigger than the max file size

**Comment by nyanpasu** [comment]
Yes, I'm a retard.
