### ISSUE TITLE
Social Media Intergration

### ISSUE THREAD

**Issue by 8n-tech** [ctrlcctrlv/infinity#466]
A popularly requested feature on 8chan is social media integration. Content should be easily shared through visible buttons on each post.

Currently supported systems:
- [ ] Facebook
- [ ] Google+
- [ ] Twitter

**Comment by Yuyukow** [comment]
>A popularly requested feature is social media integration
Does anyone really want this other than some GG twitter fags or ledditors?
I don't social media integration , i didn't even like it when cuckchan was gmail integrated.
Social media fags don't improve chan's and anons don't even really use them.
No one really wants this.

**Comment by ctrlcctrlv** [comment]
ayylmao

**Comment by ElzieDG** [comment]
No. For the love of God, Allah, or whomever you look up to, no.

**Comment by 8n-tech** [comment]
@ElzieDG Relax, it was a joke to poke fun at /operate/ freakouts.

**Comment by Imagebard** [comment]
Lotta talk for someone who is legitimately retarded
