### ISSUE TITLE
[code] tags broken by new RTL support

### ISSUE THREAD

**Issue by ctrlcctrlv** [ctrlcctrlv/infinity#471]
@8n-tech

**Comment by 8n-tech** [comment]
@ctrlctrlv Parser now encapsulates entire codeblocks.

```
Yo<code>Hello
World
Foo
Bar</code>Yo
```

Parses to

```
<p>Yo
<code>Hello<br />
World<br />
Foo<br />
Bar</code>
Yo</p>
```


Please review commit d7b511270aa561732822e8ec3683da6c469da79d
This works by RegEx.

**Comment by czaks** [comment]
I made one commit in vichan, which actually made [code] tags work. Btw. the
correct tag for multiline code is <pre>, not <code>.
20 kwi 2015 12:47 "N" <notifications@github.com> napisał(a):

**Comment by 8n-tech** [comment]
@czaks it's a <pre> within a <code> tag. I was demonstrating how the parser worked.

**Comment by czaks** [comment]
We can't tell we have a proper parser, while we have a bunch of regexps. I
still can't see how this parser handles tags, urls, unicode, another code
tags, embedded in a code tag, which by definition, should preserve the
original code. This is what my patch does. I will send, which patch is it
exactly later, but you can atm search git history for [code].
20 kwi 2015 14:16 "N" <notifications@github.com> napisał(a):

**Comment by 8n-tech** [comment]
The job of this was to parse individual lines into paragraphs that could then determine directions for international users.

If you would like to trash that in favor of what you have, go for it. I don't care.

**Comment by ctrlcctrlv** [comment]
@czaks 

We are preferring @8n-tech's parser due to RTL support. 8ch.net has one large board in Arabic (8ch.net/egy) and this is important to me, and I think it is a better direction to go for the software in case someone makes e.g. 8ch for Arab world, since the point is being international. If yours has RTL as well I can maybe switch to it. I agree with you that regex is not a proper parser.
