### ISSUE TITLE
Failing Report Captcha Returns You To the Board Index [$15]

### ISSUE THREAD

**Issue by madethisforbs** [ctrlcctrlv/infinity#481]
Currently, when you go to make a report and fail the captcha the "Go back" link in the next page returns you to the board's index. Please make it so that it takes you back to the report form, preferably with the report reason already filled out with what you had previously entered.

**Comment by ctrlcctrlv** [comment]
This is easy, I'll do it.

**Comment by ctrlcctrlv** [comment]
gibe moni plox

https://github.com/ctrlcctrlv/infinity/commit/691bc1c3fa1a866b13c07aa74af860b7c17ae33a

![1](https://cloud.githubusercontent.com/assets/838783/7332924/5b1bdc3a-eb8c-11e4-9e75-bcef1814adad.png)
