### ISSUE TITLE
Feature Request - Integrated 4chanX-esque Gallery View [$100]

### ISSUE THREAD

**Issue by madethisforbs** [ctrlcctrlv/infinity#482]
8chan should have a gallery thread viewing mode. This makes browsing threads where a comic/manga is being dumped more convenient and also has obvious use for image dump threads and boards.

I am aware that 8chanX has a gallery mode but it is clunky to use and it's layout is (in my opinion) inferior to that of the one available in 4chanX. It would also benefit all users of 8ch since it would not require a userscript and related browser addon to be installed to use. 

Example of ccd0's 4chanX Gallery View. https://github.com/ccd0/4chan-x
![4chanX Gallery View](http://a.pomf.se/xnegst.png)

I suggest the button to activate it be placed with the "Expand All Images" button and the Tree View checkbox.
![Suggested Positioning](http://a.pomf.se/ysbrdz.png)

**Comment by czaks** [comment]
i'm taking this one

**Comment by ctrlcctrlv** [comment]
okay

**Comment by czaks** [comment]
user js:

    load_js("https://pl.vichan.net/js/gallery-view.js");

user css:

    @import url('https://pl.vichan.net/stylesheets/gallery.css');

it's surely unfinished and it needs some more work, but please try and give me some feedback on it

**Comment by madethisforbs** [comment]
Hello czaks, 
Thank you for getting to this so quickly. I have tried it out and I think you are on the right track. Some kind of keyboard navigation like Up/Down arrows or W/S would be very much appreciated though.

**Comment by czaks** [comment]
Hi,
No problem. I did a few improvements, namely webm support and up/down arrow navigation. I don't believe the arrows are needed, they would clutter up the UI. Possibly, I can add some metadata display on the bottom toolbar.

**Comment by ctrlcctrlv** [comment]
pretty sure he meant using the arrow keys on the keyboard to navigate, not adding arrows to the ui

**Comment by czaks** [comment]
yeah, now i reread this post and it seems clear. anyway, it's implemented.

**Comment by madethisforbs** [comment]
Just tried it again. 

Functionality wise this is what I want but I just have a couple of style and appearance requests. Can thumbnails in the sidebar be about 75% the size of where they are now? Also can you add an indicator to the image currently being displayed in the sidebar like the 4chanX one does?

**Comment by czaks** [comment]
@madethisforbs 
about the stylesheet, sure. about the indicator, i used a box-shadow effect. it works for me in chrome. maybe it doesn't work for you, or the feedback is too small

**Comment by madethisforbs** [comment]
@czaks 
I am using Firefox 37 on Linux. I think I was just tired and didn't notice the shadow effect, I see it now. Sorry. 

I think it's pretty much fine now, thank you for your work and putting up with me.

**Comment by czaks** [comment]
i made the gallery bar a bit smaller. the changeset is now ready to be merged.

**Comment by czaks** [comment]
done, pr is merged
