### ISSUE TITLE
Board Creation Error

### ISSUE THREAD

**Issue by bwymyjymyjubwa** [ctrlcctrlv/infinity#486]
On clicking the big "Create your board" button, I and several other people have been greeted with:
Fatal error: Cannot redeclare generate_captcha() (previously declared in /srv/http/8chan-captcha/functions.php:3) in /srv/http/8chan-captcha/functions.php on line 22

**Comment by ctrlcctrlv** [comment]
sorry, it's fixed now

https://github.com/ctrlcctrlv/infinity/commit/79168cc4e16984ddb70a0894a38f0ff89d0ccd79
