### ISSUE TITLE
The first newline is deleted in code tags

### ISSUE THREAD

**Issue by ScoreUnder** [ctrlcctrlv/infinity#490]
```
[code]#!/bin/sh
echo this is some code[/code]
```
![Result](https://a.pomf.se/uzjgcu.png)

**Comment by 8n-tech** [comment]
Looking into it.

**Comment by ScoreUnder** [comment]
This is "fixed" on 8ch but it looks like a reversion of the change that broke it. I'll leave this open because I don't know if it will be reimplemented.

**Comment by 8n-tech** [comment]
It is not undoing a feature. All I changed was how large block elements 
handle line breaking.

**Comment by ScoreUnder** [comment]
I don't mean this commit, but the current code running on 8ch seems to have had the change reverted. See this screenshot:

![Screenshot](https://i.imgur.com/Ls3qqrT.png)

**Comment by 8n-tech** [comment]
That's a separate issue. If you put a line break after the first [code] tag it interprets that literally.

**Comment by ctrlcctrlv** [comment]
Closing, feature not a bug.
