### ISSUE TITLE
MySQL?

### ISSUE THREAD

**Issue by noraxx** [ctrlcctrlv/infinity#504]
You expressed you dissatisfaction with MySQL a couple of times in Twitter. My question is, do you have any plans to move to something else in the future? And if you were to start over, what would you choose?

**Comment by ctrlcctrlv** [comment]
Not a bug. This tracker is for bugs only.

https://github.com/infinity-next/infinity-next supports the database agnostic ``Doctrine'' engine, so it supports MySQL, SQLite, and Postgres OOTB.

8ch.net live site currently uses MariaDB.

**Comment by jaw-sh** [comment]
Infinity Next is database agnostic. IIRC, Copypaste plans on using 
PostgreSQL in the future.

**Comment by noraxx** [comment]
@ctrlcctrlv  @jaw-sh 
Is there a place to discuss design/architectural decisions?

**Comment by jaw-sh** [comment]
I can promise that any post made in this thread will be read.
http://8ch.net/operate/res/20692.html
