### ISSUE TITLE
Broken install.sql script

### ISSUE THREAD

**Issue by El-Metasync** [ctrlcctrlv/infinity#509]
~/infinity/$ mysql -u root -p infinity < install.sql
ERROR 1136 (21S01) at line 151: Column count doesn't match value count at row 1

The tables in my Infinity database look like this:
| antispam 
| bans
| board_create
| boards
| cites
| ip_notes
| modlogs
| mods

That's about half of them. I used Ubuntu Server 15.04 at the time of this error.

**Comment by ctrlcctrlv** [comment]
i think it's due to the new email field in the `mods` table

try editing install.sql and adding a `NULL` to the INSERT INTO `mods` line

**Comment by El-Metasync** [comment]
Yep, that seems to have done the trick.
Thank you.
