### ISSUE TITLE
We need to know when 8chan.co updates

### ISSUE THREAD

**Issue by anonfagola** [ctrlcctrlv/infinity#52]
We should have something to tell us the last time 8chan was updated to the current version of the git.

**Comment by ctrlcctrlv** [comment]
>We could display the current commit hash in the site footer.

I've been updating the site so much lately I got around to this.

Footer now reads...
`- Tinyboard + vichan + infinity a0c40b7f63 -`

It's not automatic. `echo '+ <a href="https://github.com/ctrlcctrlv/infinity">infinity</a> '`git rev-parse HEAD|head -c 10` > .installed` needs to be run every pull, I also put this command in the README.
