### ISSUE TITLE
How exactly do I use this?

### ISSUE THREAD

**Issue by anon3608** [ctrlcctrlv/infinity#524]
I apologize for asking here, but there really is no where else to ask. How do I use this? I install the packages, create a database in mysql, import the tables from install.sql (which gives me a `ERROR 1136 (21S01) at line 151: Column count doesn't match value count at row 1` error),
create the .installed file in the base directory, cp secrets.php and change them accordingly, then run rebuild.php. Then what? Running `php boards.php` returns `Error: The database returned an error while processing your request. Please try again later.
#0  error() called at [/var/www/infinity/infinity/inc/functions.php:1012]
#1  fetchBoardTags() called at [/var/www/infinity/infinity/board-search.php:143]
#2  include(/var/www/infinity/infinity/board-search.php) called at [/var/www/infinity/infinity/boards.php:13]` and no where does it say the default admin password.

I'd very much appreciate some help.

**Comment by Yushe** [comment]
There has never been a stable release of infinity all of the downloadable versions of infinity have at least one bug.

Your best bet of being able to run a somewhat functioning version of infinity is going and finding a really old fork of infinity.

**Comment by czaks** [comment]
If you don't care about an ability for users to create boards, you can try:

https://github.com/vichan-devel/vichan

Which is an imageboard engine infinity is itself based on

**Comment by ctrlcctrlv** [comment]
If you're making a new chan, use https://github.com/infinity-next/infinity-next

This project is months from being completely abandoned. It is in End-of-life.
