### ISSUE TITLE
Time out errors when uploading WEBMs

### ISSUE THREAD

**Issue by FuckfaceEmpire** [ctrlcctrlv/infinity#544]
I can upload images just fine but anytime I try to upload a WEBM the upload counter keeps restarting and eventually gives a time out error (The server took too long to submit your post...etc etc).
This also happens sometimes when I'm uploading multiple pictures that are large in size (but still within the size limit).

>0%
>1%
>2%
>...
>98%
>99%
>100%
>100%
>100%
>0%
>1%
>...

I didn't have this problem before. Today I tried posting a WEBM that I've posted about 2 months ago before, but couldn't because of this issue.

Stop fucking up the site goddammit.

**Comment by ctrlcctrlv** [comment]
Not related to the open source version of infinity.
