### ISSUE TITLE
8chan X Image Hover Doesn't Work

### ISSUE THREAD

**Issue by KrowofAgony** [ctrlcctrlv/infinity#547]
![8chanx image hover doesn t work](https://cloud.githubusercontent.com/assets/7153059/18137751/b91b359a-6f77-11e6-883a-494e02ef3a52.png)

This issue has been going on for several months.

Image Hover doesn't work properly at 8ch.net, especially when I use 8chan X Pure.

**Comment by czaks** [comment]
It's a bug of 8chan X, not infinity, you should report it there.
