### ISSUE TITLE
Random redirection to banner/ad/thumb URLs

### ISSUE THREAD

**Issue by YBRr** [ctrlcctrlv/infinity#550]
I am being randomly redirected to URLs of banners

https://softserve.8ch.net/static/stim/6c764b34772a4cce81cf79b4ce1840fc.png
https://8ch.net/file_store/thumb/a16f62010b1502979e44470635c43bb16044333a96dc5575eccb3fe2c99ddf8b.png
https://banners.8ch.net/banners/pol/1469450571964.png
https://banners.8ch.net/banners/pol/1411504000442.gif

not only right after page load but when I am writing a post too. This happened ten+ times already. There are no page modifying plugins, no AdBlock and I use HTTPS only. Happens on sys.8ch.net too

**Comment by ctrlcctrlv** [comment]
Your query relates to unrelated software, the banners.8ch.net web server software is closed source AFAICT and not part of this GitHub repository.

**Comment by YBRr** [comment]
@ctrlcctrlv I get redirected to thumbs as well!

**Comment by ctrlcctrlv** [comment]
You should probably report your issue to /sudo/; this forum was for open source development of the infinity software, which, at least as far as 8ch.net is concerned, has ceased as of June 2016. Whether it will ever start again I am not sure, but even if it does it will likely be in fits and starts as the new administration decides to release certain changes under free licenses. As such, reporting your issues _with 8chan_ to this repository makes no sense as it rarely contains a current, complete version of the code as it exists on 8chan.

**Comment by YBRr** [comment]
@ctrlcctrlv thx HW. Reported to /sudo/ before writing here, never heard back.
I got that it not your business, thanks for insight.
